-- 코드를 입력하세요
SELECT
    PT.PRODUCT_CODE,
    SUM((OS.SALES_AMOUNT)*PT.PRICE) AS SALES
FROM
    PRODUCT AS PT
JOIN
    OFFLINE_SALE AS OS
ON
    PT.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY
    PT.PRODUCT_CODE
ORDER BY
    SALES DESC, PT.PRODUCT_CODE ASC;